server {
    listen 80;
    
    # 前端代理
    location / {
        proxy_pass http://chat2anything_frontend:12345;
    }

    # 后端API代理
    location /api {
        proxy_pass http://chat2anything_backen:9988; # 始终使用容器内部端口
    }
}